### ISSUE TITLE
version 1.3.9

### ISSUE THREAD

**Issue by HRoger** [nekojira/wp-php-console#12]
Hi there ,

I got the following fatal error:

Fatal error: Uncaught exception 'Exception' with message 'PhpConsole\Connector::setPostponeStorage can be called only before PhpConsole\Connector::getInstance()' in plugins\wp-php-console\vendor\php-console\php-console\src\PhpConsole\Connector.php:80 Stack trace: #0 plugins\wp-php-console\lib\class-wp-php-console.php(73): 

Thanks

**Comment by HRoger** [comment]
Ok. Found solution:

Before updating the plugin comment out in function.php:

require_once  'wp-content/plugins/wp-php-console/vendor/autoload.php';
if ( ! class_exists( 'PC', false ) ) {
	PhpConsole\Helper::register();
}

**Comment by nekojira** [comment]
1.3.9 didn't really include changes in PHP Console

from which version were you updating?

**Comment by HRoger** [comment]
Hi from version  1.3.8.

Dont know why but in order to update had to first comment out the following code on function.php:

```php
require_once 'wp-content/plugins/wp-php-console/vendor/autoload.php';
if ( ! class_exists( 'PC', false ) ) {
PhpConsole\Helper::register();
}
```

**Comment by nekojira** [comment]
ok understood now, you had some custom code in your code, but in that case I suppose you were trying to call PhpConsole\Helper while this was unavailable during the plugin update process

you could try wrapping everything in `if ( class_exists( 'WP_PHP_Console' ) ) ...`
