### ISSUE TITLE
Wrong PHP Console eval request signature

### ISSUE THREAD

**Issue by khag7** [nekojira/wp-php-console#2]
When I try to execute from the console, I get the error indicating that the request signature does not match the signature generated by the php console library (in Auth.php).

Plugin is installed. Password is set. I am receiving E_NOTICE, E_WARNING, etc. in my console. So I know it is working.

I tried the IP address mask field (*, *.*.*.*, my own IP, blank, etc.) - they all result in the same error

I am able to use  http://162.250.145.84/php-console/examples/features/eval_terminal.php without issues, so the chrome extension is working properly.

I tried two different wordpress installs on two different hosting providers, same error.

**Comment by nekojira** [comment]
Are you having these errors also in a local environment (localhost) or just in remote servers? In the latter case might depend on server configuration? are there any http passwords set?

I've run in similar problems too when using PHP Console with WordPress (even before this plugin was made) on hosts like WPEngine, but could not duplicate the issue - I think it might have to do either with how PHP Console works and then how WordPress handles that library. I might have to do some changes in the way the plugin loads that library, but I'm not sure.

**Comment by Polfo** [comment]
I was having the same issues as @khag7
- I am receiving E_NOTICE, E_WARNING, etc. in my console fine
- I am able to use http://162.250.145.84/php-console/examples/features/eval_terminal.php

Unfortunately, I do not have a localhost running php
The issue appears on some console commands

Not on this one:
`return 2+2;`
or this one
`return $_SERVER;`

But on these ones:
`return "string";`
and
`return 'string';`
```
Exception  Wrong PHP Console eval request signature - /home/xxx/public_html/WPTestPlugin2/wp-content/plugins/wp-php-console/vendor/php-console/php-console/src/PhpConsole/Connector.php:301 
#8 /home/xxx/public_html/WPTestPlugin2/wp-content/plugins/wp-php-console/lib/class-wp-php-console.php:302 - PhpConsole\Connector->startEvalRequestsListener()
#7 [internal call] - WP_PHP_Console->init('')
#6 /home/xxx/public_html/WPTestPlugin2/wp-includes/plugin.php:496 - call_user_func_array(Array[2], Array[1])
#5 /home/xxx/public_html/WPTestPlugin2/wp-settings.php:374 - do_action('wp_loaded')
#4 /home/xxx/public_html/WPTestPlugin2/wp-config.php:85 - require_once('/home/xxx...')
#3 /home/xxx/public_html/WPTestPlugin2/wp-load.php:29 - require_once('/home/xxx...')
#2 /home/xxx/public_html/WPTestPlugin2/wp-blog-header.php:12 - require_once('/home/xxx...')
#1 /home/xxx/public_html/WPTestPlugin2/index.php:17 - require('/home/xxx...')
```

**Comment by Polfo** [comment]
New test cases below:

    return <<<EOT
    foo
    EOT;
    // works fine
.

    return <<<EOT
    "foo"
    EOT;
    // Wrong PHP Console eval request signature
.

    return <<<EOT
    "foo
    EOT;
    // Wrong PHP Console eval request signature
.

    return <<<EOT
    foo'
    EOT;
    // Wrong PHP Console eval request signature

**Comment by nekojira** [comment]
ok thanks for confirming the issue, I think I will let @barbushin, PHP Console author, know about this, maybe he can better pinpoint the cause

**Comment by barbushin** [comment]
Hi guys! Did you tried http://php.net/manual/security.magicquotes.disabling.php ?

**Comment by Polfo** [comment]
Hi @barbushin. Thanks for helping, good idea but the server runs PHP Version 5.5.17, so there is no magicquotes since this feature has removed as of PHP 5.4.0

**Comment by barbushin** [comment]
So I think the problem is that something changes request data. May be there is some PHP code in WordPress that handles request data? May be some PHP extension?

Could you guys add something like `file_put_contents('request.log', var_export($_POST, true), FILE_APPEND)` in https://github.com/nekojira/wp-php-console/blob/master/vendor/php-console/php-console/src/PhpConsole/Connector.php#L297 and attach results in this issue comments?

**Comment by Polfo** [comment]
Hello barbushin, below is the result of the log file for `return 'a'."b";` 
Note that as the error is `Wrong PHP Console eval request signature` I put the `file_put_contents` on line 301

    array (
      '__PHP_Console' => 
      array (
        'eval' => 
        array (
          'data' => 'return \\\'a\\\'.\\"b\\";
    ',
          'signature' => '736cca2523c2ed6b236108907a8b13cd561a697e1b9721521a5f949cb4ac2725',
        ),
        'getBackData' => 
        array (
          'tabId' => '12',
        ),
      ),
    )

I think only ' " and \ are escaped
// input 2:

```
return ' / \ . 
b < & é ";
``` 

// output 2:

```
'data' => 'return \\\' / \\\\ . 
b < & Ã© \\";
```

**Comment by Polfo** [comment]
Your are right @barbushin, 

We need to call http://codex.wordpress.org/Function_Reference/stripslashes_deep
The documentation says:
You may want this function when developing your own PHP application intended to run within the WordPress environment. Specifically, your program needs to strip slashes when data arrives via $_POST, $_GET, $_COOKIE, and $_REQUEST arrays.

Any idea for an elegant solution @barbushin or @nekojira? I mean one without me patching your code.

Thanks

**Comment by barbushin** [comment]
I think the simplest way to fix it, is just to add code like

```if(isset($_POST[PhpConsole\Connector::POST_VAR_NAME])) {
    $_POST[PhpConsole\Connector::POST_VAR_NAME] = stripslashes_deep($_POST[PhpConsole\Connector::POST_VAR_NAME]);
}
```
in WordPress module initialization, before any PhpConsole initialization call.

**Comment by nekojira** [comment]
thank you!

@Polfo would you like to test if @barbushin solution works for you too? if so, I will add it up

**Comment by Polfo** [comment]
I implemented barbushin proposal above in Polfo/wp-php-console#2
I works in my environment :-)

**Comment by khag7** [comment]
Gmail sent all the notification emails for this discission to my spam, sorry I missed out on the discussion. I see there was an update to the plugin on the WP repository, I'll update and test. Thanks all for your help, I'm excited to get this working on my site.
