### ISSUE TITLE
Chrome Extension no longer exists

### ISSUE THREAD

**Issue by eljeffeg** [nekojira/wp-php-console#21]
The linked [Chrome Extension](https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef) no longer exists in the Chrome store.  Any place else to download it or reason why it was removed?

**Comment by eljeffeg** [comment]
I see the post here to install in manually. https://github.com/barbushin/php-console/issues/172#issuecomment-718543168
Hope it doesn't really contain malware.

**Comment by unfulvio** [comment]
Hey @jeffg2k no it doesn't, the code is OSS and can be inspected by anyone; given the nature of the tool, though it is insecure to use in production environments (as the author warned)

A bigger problem may be that the maintainer of PHP Console (not this WP plugin) seems to be MIA and neither the plugin nor the browser extension have received significant updates in over 2 years, almost 3. 

WP Php Console still appears to work fine, but I could foresee in the future bugs to appear and I have no intention to take over Php Console. I might bundle the Chrome Extension with it, to help developers who might be puzzled by its absence in the web store. 

Alternatively I can recommend Tinkerwell or other software to achieve similar goals.

Thanks
