### ISSUE TITLE
getting fatal error when activating the plugin

### ISSUE THREAD

**Issue by ituk** [nekojira/wp-php-console#3]
Hey,
this is what i get over and over again:

Warning: require_once(__DIR__/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in /home/talgui5/public_html/moti/wp-content/plugins/wp-php-console-master/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/talgui5/public_html/moti/wp-content/plugins/wp-php-console-master/vendor/autoload.php on line 5

**Comment by nekojira** [comment]
Hi

that error tells that this file in this position:
https://github.com/nekojira/wp-php-console/blob/master/vendor/autoload.php#L5
requires a file that is not found by PHP

however the file is found here:
https://github.com/nekojira/wp-php-console/blob/master/vendor/composer/autoload_real.php
where it should be... could you check if this is true in your installation? have you installed the latest files from this repo?

the file where you get the error is generated by Composer anyway - could it be a PHP version issue or your particular configuration? have you tried installing PHP Console with composer instead with my plugin? https://github.com/barbushin/php-console

**Comment by ituk** [comment]
Thank you, I guess this is something with my php version because i already faced a problem with it before.

**Comment by squibsy** [comment]
Hi.

I get this error as well - I take it the plugin needs composer installed to work? This is not an option for me as I don't have shell access to the server I'm testing on.
https://github.com/nekojira/wp-php-console/blob/master/vendor/composer/autoload_real.php doesn't exist.
Is it possible to get a zip with all files?

**Comment by unfulvio** [comment]
the repository is meant for development 

if you want to build the plugin from git you need to run a grunt script

if you want to install the plugin you can do so from WordPress:

https://wordpress.org/plugins/wp-php-console/

**Comment by unfulvio** [comment]
ah, for future releases I will add a .zip file to the release with the built plugin, thanks

**Comment by squibsy** [comment]
Thanks - the github repository https://github.com/barbushin/php-console, when speaking about your plugin, links here rather than to the wordrpess repository. It will probably confuse others too. Thanks for your help.
