### ISSUE TITLE
Jump to file integration with WordPress editor

### ISSUE THREAD

**Issue by Polfo** [nekojira/wp-php-console#4]
Thanks for this nice integration into WP.

To avoid configuring an IDE, it would be nice to integrate the [Jump to File](https://github.com/barbushin/php-console/wiki/Jump-to-file) feature with WordPress and have the option to open the file through the /wp-admin/plugin-editor.php

**Comment by nekojira** [comment]
I see. However, the plugin editor is not really an IDE, I would not recommend to use it as an IDE nor to edit plugin files from WP dashboard, as there's no local history or VCS; if there's an accidental update all your edits might get lost or you might not figure out what file changed where.

**Comment by Polfo** [comment]
Hi, thanks for your reply. I agree there are many cases where it is not a good idea to edit files directly on the server only, so the file edit on server feature is not a priority. On the other hand, for my own code, from multiple locations and with git on the server, it can be useful.
