### ISSUE TITLE
Enhancement: Additional PHP Console Options

### ISSUE THREAD

**Issue by Polfo** [nekojira/wp-php-console#5]
It would be nice to have an option in WP PHP Console Settings to activate this code:

    // reduce displayed SourcesPath
    $connector = PhpConsole\Connector::getInstance();
    $connector->setSourcesBasePath($_SERVER['DOCUMENT_ROOT']);

**Comment by Polfo** [comment]
// and this code
	$connector->getDebugDispatcher()->detectTraceAndSource = true;

**Comment by Polfo** [comment]
and this code
	// register PC in the global namespace
	PhpConsole\Helper::register();

**Comment by nekojira** [comment]
thank you! sorry for late reply, I'm busy launching another project
